version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: lancall-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: vc
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - lancall-network

  # LanCall application
  lancall-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lancall-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/vc?authSource=admin
    volumes:
      - ./certs:/app/certs:ro
    depends_on:
      - mongodb
    networks:
      - lancall-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "https://localhost:3000/api/rooms"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lancall-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
